# Generated by Django 4.2.1 on 2023-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0002_alter_studentdata_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='student_reg_num',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
