# Generated by Django 4.2.1 on 2023-05-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0003_studentdata_student_reg_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='student_reg_num',
        ),
    ]
