# Generated by Django 4.2.1 on 2023-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0004_remove_studentdata_student_reg_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='stu_red_id',
            field=models.CharField(default='UNI<django.db.models.fields.BigAutoField>', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
