# Generated by Django 4.2.1 on 2023-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0005_studentdata_stu_red_id_alter_studentdata_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='stu_red_id',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='stu_reg_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
