# Generated by Django 4.2.1 on 2023-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0006_remove_studentdata_stu_red_id_studentdata_stu_reg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='course_status',
            field=models.IntegerField(default=-1, max_length=1),
        ),
    ]
