# Generated by Django 4.2.1 on 2023-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0007_alter_studentdata_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='course_status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
