# Generated by Django 4.2.1 on 2023-05-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0009_rename_course_registered_studentdata_course_reg_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursedata',
            table='Courses',
        ),
    ]
