# Generated by Django 4.2.1 on 2023-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0010_alter_coursedata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='course_name',
            field=models.CharField(default='none', max_length=16, null=True, unique=True),
        ),
    ]
