# Generated by Django 4.2.1 on 2023-05-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0011_alter_coursedata_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='course_reg_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.coursedata'),
        ),
    ]
