# Generated by Django 4.2.1 on 2023-05-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0014_alter_studentdata_course_reg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='course_name',
            field=models.CharField(max_length=16, null='True', unique='True'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='course_reg_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.coursedata'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='stu_reg_id',
            field=models.CharField(max_length=50, null='True', unique='True'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_id',
            field=models.BigAutoField(auto_created='True', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_image',
            field=models.ImageField(null='True', upload_to=''),
        ),
    ]
