# Generated by Django 4.2.1 on 2023-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0015_alter_coursedata_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='course_status',
            field=models.IntegerField(default=0),
        ),
    ]
