# Generated by Django 4.2.1 on 2023-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0016_alter_studentdata_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student_image',
            field=models.ImageField(null='True', upload_to='events/static/images/'),
        ),
    ]
