# Generated by Django 4.2.1 on 2023-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0021_alter_studentdata_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student_image',
            field=models.ImageField(default=None, null='True', upload_to='images/'),
        ),
    ]
