# Generated by Django 4.2.1 on 2023-05-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0024_alter_studentdata_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='course_reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stu_cou_reg.coursedata'),
        ),
    ]
