# Generated by Django 4.2.1 on 2023-05-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0025_alter_studentdata_course_reg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='course_reg_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.coursedata'),
        ),
    ]
