# Generated by Django 4.2.1 on 2023-05-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0026_alter_studentdata_course_reg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='course_reg_id',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='course_status',
        ),
        migrations.CreateModel(
            name='Regisatered',
            fields=[
                ('regisatered_id', models.BigAutoField(auto_created='True', primary_key=True, serialize=False)),
                ('course_status', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.coursedata')),
                ('student_id', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.studentdata')),
            ],
        ),
    ]
