# Generated by Django 4.2.1 on 2023-05-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0027_remove_studentdata_course_reg_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regisatered',
            table='Regisatered',
        ),
    ]
