# Generated by Django 4.2.1 on 2023-05-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0029_alter_studentdata_student_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regisatered',
            new_name='RegisteredData',
        ),
        migrations.RenameField(
            model_name='registereddata',
            old_name='regisatered_id',
            new_name='registered_id',
        ),
    ]
