# Generated by Django 4.2.1 on 2023-05-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_cou_reg', '0030_rename_regisatered_registereddata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddata',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.coursedata'),
        ),
        migrations.AlterField(
            model_name='registereddata',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_cou_reg.studentdata'),
        ),
    ]
